source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-content-for'
gem 'git'
gem 'bluecloth'
gem 'rubypants'
# gem 'redcarpet'
gem 'shotgun'
gem 'time-ago-in-words'
gem 'encrypted_cookie'
gem 'mixlib-config'
gem 'sinatra-flash'
gem 'unicorn'

